-- Seeds the twelve App Review demo profiles.
--
-- Run this in the Supabase SQL editor (Dashboard -> SQL Editor -> New query).
-- It is idempotent: running it twice is harmless and simply refreshes the
-- content. It creates nothing that a real student can see.
--
-- WHY THIS IS A FILE AND NOT A MIGRATION: it writes to auth.users, which is
-- Supabase-managed. The accounts are deliberately passwordless - nobody ever
-- signs in as a demo profile, they only need to exist so that profiles.id
-- (FK -> auth.users.id) resolves and so swipes/matches/messages can reference
-- them.
--
-- Artwork is served from the app's own origin (public/demo/, generated by
-- scripts/gen-demo-photos.py), NOT Supabase storage. Storage objects are
-- owned by the uploading auth user, so deleting demo accounts orphans every
-- URL - which is exactly how the demo feed broke once before.
--
-- Coverage: 6 dorm + 6 apartment, and within each pool 2 girl / 2 guy /
-- 2 nonbinary. gendersCompatible() in src/lib/compatibility.js is symmetric
-- (same-gender matches, nonbinary sees and is seen by everyone), so whichever
-- gender AND housing type the reviewer picks, at least four profiles appear.

begin;

-- 1. Passwordless auth users -------------------------------------------------
insert into auth.users (
  instance_id, id, aud, role, email, email_confirmed_at,
  created_at, updated_at, raw_app_meta_data, raw_user_meta_data,
  is_sso_user, is_anonymous
)
select '00000000-0000-0000-0000-000000000000', v.id, 'authenticated', 'authenticated',
       v.email, now(), now(), now(),
       '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, false, false
from (values
  ('a7f3c9d1-2b48-4e6a-9c15-8d3f0e7a41b2'::uuid, 'jordan@demo.getlik.com'),
  ('c4e81b70-5a29-4d13-8f6b-2e9c7a5d0f38'::uuid, 'sam@demo.getlik.com'),
  ('f2b6d045-8c31-4a97-b5e2-6f1a9d47c803'::uuid, 'riley@demo.getlik.com'),
  ('3d9a7e52-1f64-4c80-a736-b8e2f0d5194c'::uuid, 'casey@demo.getlik.com'),
  ('1c18a0f1-e6d9-4568-89e7-477a2da5aacc'::uuid, 'priya@demo.getlik.com'),
  ('4b92b493-9890-4d8f-aafc-8eed67012608'::uuid, 'maya@demo.getlik.com'),
  ('bb8fc121-60f4-474f-8b65-4c27ac944074'::uuid, 'andre@demo.getlik.com'),
  ('9ad5f70e-9dc2-4604-b31b-ee44fb85e7c6'::uuid, 'tomas@demo.getlik.com'),
  ('6dee0415-a81a-4c1d-b90d-d6660bd86491'::uuid, 'ava@demo.getlik.com'),
  ('e197aba8-9ab1-4d81-b3d6-7dd9c5036f7d'::uuid, 'nadia@demo.getlik.com'),
  ('02624763-564d-4bf2-9704-3c3acd8a3816'::uuid, 'devin@demo.getlik.com'),
  ('35cc7cd0-5174-4904-b844-31e826b176c7'::uuid, 'marcus@demo.getlik.com')
) as v(id, email)
on conflict (id) do nothing;

-- handle_new_user() creates the profiles row from that insert; this fills it in.

-- 2. Profile content ---------------------------------------------------------
with seed(id, slug, name, age, gender, year, major, housing_type, bio, caption,
          move_in, dorm_prefs, areas, budget_min, budget_max, dealbreakers, quiz) as (
  values
  -- ---------------- dorm pool ----------------
  ('a7f3c9d1-2b48-4e6a-9c15-8d3f0e7a41b2'::uuid, 'jordan', 'Jordan Vasquez', 20, 'nonbinary', 'Sophomore', 'Psychology', 'dorm',
   'Up before my alarm most days and useless until coffee. I keep shared space clean without being weird about it, and I go quiet in the last two weeks of a semester.',
   'A pretty ordinary week', 'Fall 2026',
   array['Illinois Street (ISR)','Wassaja Hall','Bousfield Hall'], array[]::text[], null::int, null::int,
   array['smoke_free','quiet_after_midnight'],
   '{"sleep":"a","tidy":"a","noise":"a","guests":"a","weekend":"a","temp":"a","kitchen":"a","sharing":"a","conflict":"a","alarm":"a","study":"a","vibe":"b"}'::jsonb),

  ('c4e81b70-5a29-4d13-8f6b-2e9c7a5d0f38'::uuid, 'sam', 'Sam Okafor', 19, 'nonbinary', 'Freshman', 'Computer Science', 'dorm',
   'Night owl, mostly at Grainger until it closes. I actually cook dinner and I will feed you, but I run cold and I am not negotiating on the thermostat.',
   'Mostly campus, mostly late', 'Fall 2026',
   array['Nugent Hall','Scott Hall'], array[]::text[], null::int, null::int,
   array['substance_free','night_noise_ok'],
   '{"sleep":"b","tidy":"b","noise":"b","guests":"b","weekend":"b","temp":"a","kitchen":"a","sharing":"b","conflict":"b","alarm":"b","study":"b","vibe":"a"}'::jsonb),

  ('1c18a0f1-e6d9-4568-89e7-477a2da5aacc'::uuid, 'priya', 'Priya Raghunathan', 19, 'girl', 'Sophomore', 'Molecular and Cellular Biology', 'dorm',
   'Pre-med sophomore, up at six whether I like it or not. I cook a lot of South Indian food and I will absolutely feed you. Clean kitchen or I lose my mind.',
   'Home cooking and long library days', 'Fall 2026',
   array['Illinois Street (ISR)','Busey Evans Hall'], array[]::text[], null::int, null::int,
   array['smoke_free','veg_kitchen','quiet_after_midnight'],
   '{"sleep":"a","tidy":"a","noise":"a","guests":"a","weekend":"a","temp":"b","kitchen":"a","sharing":"a","conflict":"a","alarm":"a","study":"b","vibe":"a"}'::jsonb),

  ('4b92b493-9890-4d8f-aafc-8eed67012608'::uuid, 'maya', 'Maya Ellison', 18, 'girl', 'Freshman', 'Journalism', 'dorm',
   'Freshman from Naperville, still figuring out the bus system. I am tidy, I go to bed early on weeknights, and I am looking for someone I can actually talk to.',
   'First year, still exploring', 'Fall 2026',
   array['Allen Hall','Lincoln Avenue (LAR)','Trelease Hall'], array[]::text[], null::int, null::int,
   array['smoke_free','quiet_after_midnight'],
   '{"sleep":"a","tidy":"a","noise":"b","guests":"a","weekend":"a","temp":"b","kitchen":"b","sharing":"b","conflict":"a","alarm":"b","study":"b","vibe":"a"}'::jsonb),

  ('bb8fc121-60f4-474f-8b65-4c27ac944074'::uuid, 'andre', 'Andre Whitfield', 20, 'guy', 'Junior', 'Mechanical Engineering', 'dorm',
   'Junior in MechE, so I am in the lab more than the room. Quiet, easy to live with, and I clean up after myself without anyone asking.',
   'Mostly in the lab', 'Fall 2026',
   array['Daniels Hall (Grad)','Nugent Hall'], array[]::text[], null::int, null::int,
   array['substance_free','quiet_after_midnight'],
   '{"sleep":"a","tidy":"a","noise":"a","guests":"a","weekend":"a","temp":"a","kitchen":"b","sharing":"a","conflict":"b","alarm":"a","study":"b","vibe":"b"}'::jsonb),

  ('9ad5f70e-9dc2-4604-b31b-ee44fb85e7c6'::uuid, 'tomas', 'Tomas Herrera', 19, 'guy', 'Sophomore', 'Economics', 'dorm',
   'Sophomore, big on intramural soccer and bad reality TV. Social most nights but I respect a closed door and headphones on.',
   'Weeknights are for soccer', 'Fall 2026',
   array['Scott Hall','Weston Hall','Hopkins Hall'], array[]::text[], null::int, null::int,
   array['smoke_free','guests_anytime'],
   '{"sleep":"b","tidy":"b","noise":"b","guests":"b","weekend":"b","temp":"a","kitchen":"b","sharing":"b","conflict":"a","alarm":"b","study":"a","vibe":"a"}'::jsonb),

  -- ---------------- apartment pool ----------------
  ('f2b6d045-8c31-4a97-b5e2-6f1a9d47c803'::uuid, 'riley', 'Riley Chen', 21, 'nonbinary', 'Junior', 'Marketing', 'apartment',
   'Loud in the kitchen, dead quiet after midnight. I want a place that feels lived in and a roommate who splits chores without anyone building a spreadsheet.',
   'Around town', 'Fall 2026',
   array[]::text[], array['Campustown','Downtown Champaign','Green Street'], 700, 1100,
   array['quiet_after_midnight','pet_allergy'],
   '{"sleep":"a","tidy":"b","noise":"b","guests":"b","weekend":"b","temp":"b","kitchen":"a","sharing":"b","conflict":"a","alarm":"b","study":"a","vibe":"a"}'::jsonb),

  ('3d9a7e52-1f64-4c80-a736-b8e2f0d5194c'::uuid, 'casey', 'Casey Brennan', 22, 'nonbinary', 'Senior', 'Economics', 'apartment',
   'Applying to grad school, so I am at the library more than I am home. Tidy, low drama, and I will always text before I bring people over.',
   'Weekends off campus', 'Fall 2026',
   array[]::text[], array['West Urbana','Downtown Urbana'], 650, 950,
   array['smoke_free','no_overnight_guests','veg_kitchen'],
   '{"sleep":"a","tidy":"a","noise":"a","guests":"a","weekend":"a","temp":"b","kitchen":"a","sharing":"a","conflict":"b","alarm":"a","study":"b","vibe":"b"}'::jsonb),

  ('6dee0415-a81a-4c1d-b90d-d6660bd86491'::uuid, 'ava', 'Ava Lindqvist', 21, 'girl', 'Junior', 'Graphic Design', 'apartment',
   'Design junior, which means my desk is chaos and the rest of the apartment is spotless. Looking for a lease with someone who cooks and does not mind a plant collection.',
   'Studio, coffee, repeat', 'Fall 2026',
   array[]::text[], array['Campustown','Midtown Champaign'], 750, 1150,
   array['smoke_free','pet_home'],
   '{"sleep":"b","tidy":"b","noise":"b","guests":"a","weekend":"a","temp":"b","kitchen":"a","sharing":"b","conflict":"a","alarm":"b","study":"a","vibe":"a"}'::jsonb),

  ('e197aba8-9ab1-4d81-b3d6-7dd9c5036f7d'::uuid, 'nadia', 'Nadia Osman', 22, 'girl', 'Senior', 'Community Health', 'apartment',
   'Senior, mostly working or at the gym. I keep things clean, I split chores evenly, and I would rather solve a problem the day it happens than let it sit.',
   'Gym, work, repeat', 'Spring 2027',
   array[]::text[], array['West Urbana','East Urbana','Downtown Urbana'], 600, 900,
   array['substance_free','no_overnight_guests'],
   '{"sleep":"a","tidy":"a","noise":"a","guests":"a","weekend":"a","temp":"a","kitchen":"a","sharing":"a","conflict":"a","alarm":"a","study":"a","vibe":"b"}'::jsonb),

  ('02624763-564d-4bf2-9704-3c3acd8a3816'::uuid, 'devin', 'Devin Park', 22, 'guy', 'Senior', 'Information Sciences', 'apartment',
   'Senior in the iSchool. I work from home most days so a quiet apartment matters to me. I cook dinner most nights and I am happy to share.',
   'Home office, most days', 'Fall 2026',
   array[]::text[], array['South Campus · Research Park','Savoy'], 800, 1250,
   array['smoke_free','quiet_after_midnight','no_pets'],
   '{"sleep":"a","tidy":"a","noise":"a","guests":"a","weekend":"a","temp":"b","kitchen":"a","sharing":"a","conflict":"b","alarm":"a","study":"a","vibe":"b"}'::jsonb),

  ('35cc7cd0-5174-4904-b844-31e826b176c7'::uuid, 'marcus', 'Marcus Bell', 21, 'guy', 'Junior', 'Sports Media', 'apartment',
   'Junior in Sports Media. Games on in the living room most weekends, but I am dead quiet after midnight. Looking for somewhere close to campus.',
   'Game day, every weekend', 'Fall 2026',
   array[]::text[], array['Campustown','Green Street','North Champaign'], 700, 1000,
   array['four20_friendly','night_noise_ok'],
   '{"sleep":"b","tidy":"b","noise":"b","guests":"b","weekend":"b","temp":"a","kitchen":"b","sharing":"b","conflict":"b","alarm":"b","study":"a","vibe":"a"}'::jsonb)
)
insert into profiles as p (
  id, email, name, age, gender, year, major, housing_type, bio, photo_caption,
  move_in, dorm_prefs, areas, budget_min, budget_max, dealbreakers, quiz,
  profile_pic_url, photos, is_demo, onboarding_step
)
select
  s.id,
  s.slug || '@demo.getlik.com',
  s.name, s.age, s.gender, s.year, s.major, s.housing_type, s.bio, s.caption,
  s.move_in, s.dorm_prefs, s.areas, s.budget_min, s.budget_max, s.dealbreakers, s.quiz,
  -- Root-relative on purpose, NOT https://getlik.com/... . Capacitor copies
  -- build/ into the app bundle, so inside the iOS app these resolve against
  -- capacitor://localhost and load straight off disk: no network, no CDN, and
  -- nothing the Vercel firewall can challenge. An <img> that receives a bot
  -- challenge page just fails to render, and a WKWebView cannot solve one.
  -- On the web build they resolve against the app's own origin as usual.
  '/demo/' || s.slug || '-avatar.webp',
  array[
    '/demo/' || s.slug || '-1.webp',
    '/demo/' || s.slug || '-2.webp',
    '/demo/' || s.slug || '-3.webp',
    '/demo/' || s.slug || '-4.webp',
    '/demo/' || s.slug || '-5.webp',
    '/demo/' || s.slug || '-6.webp'
  ],
  true,
  'done'
from seed s
on conflict (id) do update set
  name = excluded.name, age = excluded.age, gender = excluded.gender,
  year = excluded.year, major = excluded.major, housing_type = excluded.housing_type,
  bio = excluded.bio, photo_caption = excluded.photo_caption,
  move_in = excluded.move_in, dorm_prefs = excluded.dorm_prefs, areas = excluded.areas,
  budget_min = excluded.budget_min, budget_max = excluded.budget_max,
  dealbreakers = excluded.dealbreakers, quiz = excluded.quiz,
  profile_pic_url = excluded.profile_pic_url, photos = excluded.photos,
  is_demo = true, onboarding_step = 'done';

-- 3. Keep demo rows off real students' devices -------------------------------
-- The feed already filters is_demo client-side, but the old SELECT policy was
-- `true`, so every real user's client still downloaded the demo rows. This
-- makes the server refuse to send them to anyone but the review account.
drop policy if exists "profiles readable by authed" on profiles;
create policy "profiles readable by authed" on profiles
  for select using (
    not coalesce(is_demo, false)
    or id = auth.uid()
    or coalesce(auth.jwt() ->> 'email', '') = 'applereview@getlik.com'
  );

commit;

-- 4. Check ------------------------------------------------------------------
select housing_type, gender, count(*)
from profiles where is_demo
group by housing_type, gender
order by housing_type, gender;
